[project]
name = "invite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "tomli>=2.0.1",
    "typer>=0.20.0",
]

[project.scripts]
invite = "invite.cli:app"

[tool.uv]
package = true
